version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis_cache
    networks:
      - app-network

  backend:
    build: ./backend/myproject
    container_name: django_backend
    depends_on:
      - db
      - redis
    environment:
      # Django superuser
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: adminpass

      # PostgreSQL
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db

      # Redis
      REDIS_HOST: redis
    ports:
      - "8080:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react_frontend
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
